### ISSUE TITLE
extract_fields doesn't work with generics

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#141]
```python
>>> @extract_fields(fields={"gvars" : List[str]})
... def parameters(params: Dict[str, Any]) -> Any:
...     return params
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/elijahbenizzy/dev/dagworks/os/hamilton/hamilton/function_modifiers/expanders.py", line 731, in __init__
    raise base.InvalidDecoratorException(
hamilton.function_modifiers.base.InvalidDecoratorException: Error, found these ['gvars does not declare a type. Instead it passes typing.List[str].']. Please pass in a dict of string to types.
```

**Comment by skrawcz** [comment]
this was fixed
