### ISSUE TITLE
Bug Report in my_script.py and notebook.ipynb

### ISSUE THREAD

**Issue by JoJo10Smith** [DAGWorks-Inc/hamilton#380]
# Current behavior
I noticed a bug while developing with the to.sql example in the `my_script.py` and the `notebook.ipynb` where a value error was being caused since the scripts attempt to create a table named `test` but if that table already exists (by running the script multiple times) it will cause a `ValueError`

## Stack Traces
`my_script.py`

```
Traceback (most recent call last):
  File "/home/jordan/Desktop/OpenSource/hamilton-js/examples/pandas/materialization/my_script.py", line 91, in <module>
    materialization_results, additional_outputs = dr.materialize(
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/driver.py", line 1007, in materialize
    raw_results = self.graph_executor.execute(
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/driver.py", line 161, in execute
    fg.execute(nodes, memoized_computation, overrides, inputs)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/graph.py", line 556, in execute
    return execute_subdag(
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/execution/graph_functions.py", line 157, in execute_subdag
    dfs_traverse(final_var_node, dep_type)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/execution/graph_functions.py", line 146, in dfs_traverse
    value = adapter.execute_node(node_, kwargs)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/base.py", line 504, in execute_node
    return node.callable(**kwargs)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/function_modifiers/adapters.py", line 492, in save_data
    return data_saver.save_data(data_to_save)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/plugins/pandas_extensions.py", line 505, in save_data
    results = data.to_sql(self.table_name, self.db_connection, **self._get_saving_kwargs())
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2440, in to_sql
    table.create()
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 927, in create
    raise ValueError(f"Table '{self.name}' already exists.")
ValueError: Table 'test' already exists.
```

`notebook.ipynb`
```
Node df_to_sql encountered an error
Traceback (most recent call last):
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/execution/graph_functions.py", line 146, in dfs_traverse
    value = adapter.execute_node(node_, kwargs)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/base.py", line 504, in execute_node
    return node.callable(**kwargs)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/function_modifiers/adapters.py", line 492, in save_data
    return data_saver.save_data(data_to_save)
  File "/home/jordan/Desktop/OpenSource/hamilton-js/hamilton/plugins/pandas_extensions.py", line 506, in save_data
    return utils.get_sql_metadata(self.table_name, results)
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 2440, in to_sql
    table.create()
  File "/home/jordan/.local/lib/python3.10/site-packages/pandas/io/sql.py", line 927, in create
    raise ValueError(f"Table '{self.name}' already exists.")
ValueError: Table 'test' already exists.
```

## Screenshots

`notbook.ipynb` with the same error in the `my_script.py`

![image](https://github.com/DAGWorks-Inc/hamilton/assets/64989097/c867b3ea-8f08-44c2-8c84-e700f025c992)

![image](https://github.com/DAGWorks-Inc/hamilton/assets/64989097/f355f0c7-41cc-4aa0-9b47-566b65d578eb)

## Steps to replicate behavior
1. Run the `my_script.py` file multiple times or the code block in the `notebook.ipynb` file that starts with "materialize a result, i.e. execute the DAG!"

## Library & System Information
Python version: 3.10
Hamilton library version: 1.29.0
OS: Ubuntu 22.04

# Expected behavior
The code should not cause a `ValueError`

# Additional context
This is a relatively simple fix and I will submit a PR with the code changes.

**Comment by JoJo10Smith** [comment]
Closing since this issue has been solved.
