### ISSUE TITLE
Unable to correctly use `Annotated` NumPy types

### ISSUE THREAD

**Issue by brocksam** [DAGWorks-Inc/hamilton#554]
I want to use `Annotated` NumPy types with Hamilton to enable us to better keep track of array shapes in large DAGs with different array sizes. I've done this currently using a combination of `Annotated`, `Literal`, and `TypeVar` from the `typing` module. Hamilton doesn't allow this and (I believe) incorrectly raises a `ValueError` stopping the pipeline from running. To get round this I'm having to currently type certain arrays as `npt.NDArray`, which means I end up missing out on the extra array information conveyed in the type hints.

# Current behavior
Raises a `ValueError` about mismatched types that are not mismatched.

## Stack Traces
```
Traceback (most recent call last):
  File "/Users/brocksam/Documents/hamilton/reproducer.py", line 7, in <module>
    dr = driver.Driver(
         ^^^^^^^^^^^^^^
  File "/Users/brocksam/Installs/miniconda3/envs/test-env/lib/python3.11/site-packages/hamilton/driver.py", line 293, in __init__
    raise e
  File "/Users/brocksam/Installs/miniconda3/envs/test-env/lib/python3.11/site-packages/hamilton/driver.py", line 288, in __init__
    self.graph = graph.FunctionGraph.from_modules(*modules, config=config, adapter=adapter)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brocksam/Installs/miniconda3/envs/test-env/lib/python3.11/site-packages/hamilton/graph.py", line 520, in from_modules
    nodes = create_function_graph(*modules, config=config, adapter=adapter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brocksam/Installs/miniconda3/envs/test-env/lib/python3.11/site-packages/hamilton/graph.py", line 129, in create_function_graph
    nodes = update_dependencies(nodes, adapter, reset_dependencies=False)  # no dependencies
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brocksam/Installs/miniconda3/envs/test-env/lib/python3.11/site-packages/hamilton/graph.py", line 94, in update_dependencies
    add_dependency(n, node_name, nodes, param_name, param_type, adapter)
  File "/Users/brocksam/Installs/miniconda3/envs/test-env/lib/python3.11/site-packages/hamilton/graph.py", line 56, in add_dependency
    raise ValueError(
ValueError: Error: second is expecting first:numpy.ndarray[typing.Any, numpy.dtype[numpy.float64]], but found first:typing.Annotated[numpy.ndarray[typing.Any, numpy.dtype[numpy.float64]], typing.Literal['N']]. 
Hamilton does not consider these types to be equivalent. If you believe they are equivalent, please reach out to the developers.Note that, if you have types that are equivalent for your purposes, you can create a graph adapter that checks the types against each other in a more lenient manner.
```

## Screenshots
(If applicable)

## Steps to replicate behavior
Here is a minimal reproducer, will need NumPy installed.

```python
# transforms.py
from typing import Annotated, Literal, TypeVar

import numpy as np
import numpy.typing as npt

DType = TypeVar("DType", bound=np.generic)
ArrayN = Annotated[npt.NDArray[DType], Literal["N"]]


def first() -> ArrayN[np.float64]:
    return np.array([1, 2, 3])


def second(first: ArrayN[np.float64], other: float = 2.0) -> ArrayN[np.float64]:
    return first * other
```

```python
# reproducer.py
import transforms
from hamilton import driver
from hamilton.base import DictResult, SimplePythonGraphAdapter

if __name__ == '__main__':
    config = {}
    dr = driver.Driver(
        config,
        transforms,
        adapter=SimplePythonGraphAdapter(DictResult()),
    )
    output = dr.execute(["second"])
```

Interestingly, using `Annotated` doesn't seem to cause issue if annotating other types like `int`, just `numpy.typing.NDArray` like in the reproducer.

## Library & System Information
macOS, Python 3.11.6, Hamilton 1.37.1, NumPy 1.26.1

# Expected behavior
I believe that this is sanely typed and shouldn't error. Hamilton should be treating `first` typed as `typing.Annotated[numpy.ndarray[typing.Any, numpy.dtype[numpy.float64]], typing.Literal['N']]` when passed as an argument to `second`.

# Additional context

**Comment by skrawcz** [comment]
@brocksam nice to see you! Thanks for the issue. Makes sense.

Otherwise how blocked are you on this? As the error message suggest, you could write quick graph adapter that overrides the function that checks that types match. 

something like (haven't test this ... but something like it):
```python
from hamilton import base

class MyAdapter(base.SimplePythonGraphAdapter):
 
    @staticmethod
    def check_input_type(node_type: Type, input_value: Any) -> bool:
         # this checks inputs to the DAG against the expected type of the input
         return ...

    @staticmethod
    def check_node_type_equivalence(node_type: Type, input_type: Type) -> bool:
        # this is what Hamilton uses to check whether node output from one matches the input to another
        # e.g. add logic to check for annotated here...
        return ...
```

**Comment by skrawcz** [comment]
@brocksam I think it's a quick fix -- should be able to push this out Monday.

**Comment by skrawcz** [comment]
This will go out Monday.

**Comment by brocksam** [comment]
Thanks for fixing this so quickly, @skrawcz! We'll upgrade to the latest version when released next week.

(P.S. From the above I'm quite clearly back using Hamilton, but in a completely different industry. Thanks for the great, easy-to-use package!)
