### ISSUE TITLE
OSError when using jupyter magic in databricks notebook due to missing source code

### ISSUE THREAD

**Issue by elijahbenizzy** [DAGWorks-Inc/hamilton#771]
Short description explaining the high-level reason for the new issue.

# Current behavior
In one cell:

```python
%%cell_to_module -m test --display
def foo() -> int:
    pass
```

In next cell:
```python
from hamilton import node
from hamilton.graph_types import HamiltonNode
import test
n = node.Node.from_fn(foo)
dr = driver.Driver({}, test)
var = dr.list_available_variables()[0]
var.version
```

## Stack Traces
```python
raceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<command-2983067552043610>", line 7, in <module>
    var.version
  File "/usr/lib/python3.9/functools.py", line 969, in __get__
    val = self.func(instance)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4c459acb-42c0-448b-bd4f-511f5ba39d33/lib/python3.9/site-packages/hamilton/graph_types.py", line 151, in version
    return hash_source_code(self.originating_functions[0], strip=True)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-4c459acb-42c0-448b-bd4f-511f5ba39d33/lib/python3.9/site-packages/hamilton/graph_types.py", line 71, in hash_source_code
    source = inspect.getsource(source)
  File "/usr/lib/python3.9/inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python3.9/inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.9/inspect.py", line 835, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 1997, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1112, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 1006, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 859, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 812, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/databricks/python/lib/python3.9/site-packages/IPython/core/ultratb.py", line 730, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/databricks/python/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/core.py", line 698, in lines
    pieces = self.included_pieces
  File "/databricks/python/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/core.py", line 649, in included_pieces
    pos = scope_pieces.index(self.executing_piece)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/utils.py", line 145, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/databricks/python/lib/python3.9/site-packages/stack_data/core.py", line 628, in executing_piece
    return only(
  File "/databricks/python/lib/python3.9/site-packages/executing/executing.py", line 164, in only
    raise NotOneValueFound('Expected one value, found 0')
executing.executing.NotOneValueFound: Expected one value, found 0
```
Note that this is fixed by #770, but we should fix the underlying error.

Here's the repro for that case:

```python
from hamilton.graph_types import hash_source_code
hash_source_code(var.originating_functions[0])
```

**Comment by zilto** [comment]
According to the error, the repro above seems to miss the core issue. The error message points to `inspect.getsource` within `hash_source_code`. This in return relates to `module_from_source` ([ref](https://github.com/DAGWorks-Inc/hamilton/blob/9521df54f8d6400917037250c050481233a19c00/hamilton/ad_hoc_utils.py#L63)) which should be used behind the scene in the Jupyter magic.

Suggested repro:
```python
from hamilton import node
from hamilton.graph_types import HamiltonNode
import test
n = node.Node.from_fn(foo)
dr = driver.Driver({}, test)
var = dr.list_available_variables()[0]
var.version
```

At the core, we want to check (might be inexact since I don't have access to databricks):
```python
import inspect
import textwrap
from hamilton.ad_hoc_utils import module_from_source
from hamilton.graph_types import hash_source_code

source = textwrap.dedent("""
def foo() -> int:
    pass
""")
module = module_from_source(source)

inspect.getsource(module.foo)
hash_source_code(module.foo)
```
